package hr.project;

import hr.algebra.utils.MessageUtils;
import hr.project.dal.Repository;
import hr.project.dal.RepositoryFactory;
import hr.project.model.Addable;
import hr.project.model.Genre;
import java.awt.Dialog;
import java.util.Set;
import java.util.TreeSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Goran
 */
public class GenresPanel extends javax.swing.JPanel implements Addable {

    private static final String ADD_NEW_TITLE = "Add new genre";
    private Repository repository;
    private final Set<Genre> genres = new TreeSet<>((Genre g1, Genre g2)
            -> g1.getName().toUpperCase().compareTo(g2.getName().toUpperCase()));
    private DefaultListModel<Genre> genresModel = new DefaultListModel<>();

    public GenresPanel() {
        initComponents();
        loadGenres();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblEditGenre = new javax.swing.JLabel();
        spGenres = new javax.swing.JScrollPane();
        lsGenres = new javax.swing.JList<>();
        btnNew = new javax.swing.JButton();
        lblGenres = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnReload = new javax.swing.JButton();
        lblNameError = new javax.swing.JLabel();

        lblEditGenre.setText("Name");

        lsGenres.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        lsGenres.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lsGenresValueChanged(evt);
            }
        });
        spGenres.setViewportView(lsGenres);

        btnNew.setText("New genre");
        btnNew.setActionCommand("New");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        lblGenres.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblGenres.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGenres.setText("Genres");

        tfName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tfNameMouseClicked(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete genre");
        btnDelete.setActionCommand("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnReload.setText("Reload genres");
        btnReload.setActionCommand("Reload");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });

        lblNameError.setForeground(java.awt.Color.red);
        lblNameError.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnNew, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblEditGenre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfName)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnReload, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(lblGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnReload, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(lblEditGenre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNameError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(spGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnNew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lsGenresValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lsGenresValueChanged
        lblNameError.setText("");
        Genre genre = lsGenres.getSelectedValue();
        if (genre != null) {
            tfName.setText(genre.getName());
        }
    }//GEN-LAST:event_lsGenresValueChanged

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed

        new AddNewDialog((JFrame) SwingUtilities.windowForComponent(this),
                Dialog.ModalityType.APPLICATION_MODAL, ADD_NEW_TITLE).setVisible(true);
    }//GEN-LAST:event_btnNewActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if (lsGenres.getSelectedValue() != null && isFormValid()) {
            Genre genre = new Genre(lsGenres.getSelectedValue().getId(), tfName.getText().trim());
            if (!genres.contains(genre)) {
                try {
                    repository.genreUpdate(lsGenres.getSelectedValue().getId(), genre);
                    genres.remove(lsGenres.getSelectedValue());
                    genres.add(genre);
                    loadGenresModel();
                } catch (Exception ex) {
                    MessageUtils.showInformationMessage("Error", "Error updating genre");
                    Logger.getLogger(GenresPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
            clearForm();
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        clearForm();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Genre genre = lsGenres.getSelectedValue();
        if (genre != null) {
            try {
                repository.genreDelete(genre.getId());
                genres.remove(genre);
                loadGenresModel();
                clearForm();
            } catch (Exception ex) {
                MessageUtils.showInformationMessage("Error", "Error deleting genre");
                Logger.getLogger(GenresPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        genres.clear();
        loadGenres();
    }//GEN-LAST:event_btnReloadActionPerformed

    private void tfNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tfNameMouseClicked
        lblNameError.setText("");
    }//GEN-LAST:event_tfNameMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnReload;
    private javax.swing.JLabel lblEditGenre;
    private javax.swing.JLabel lblGenres;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JList<Genre> lsGenres;
    private javax.swing.JScrollPane spGenres;
    private javax.swing.JTextField tfName;
    // End of variables declaration//GEN-END:variables

    private void loadGenres() {
        try {
            repository = RepositoryFactory.getRepository();
            genres.addAll(repository.genresSelectAll());
            loadGenresModel();
        } catch (Exception ex) {
            MessageUtils.showErrorMessage("Error", "Unable to load genres");
        }
    }

    private boolean isFormValid() {
        boolean valid = true;

        if (tfName.getText().trim().isEmpty()) {
            lblNameError.setText("X");
            valid = false;
        } else {
            lblNameError.setText("");
        }

        return valid;
    }

    private void loadGenresModel() {
        genresModel.clear();
        genres.forEach(genresModel::addElement);
        lsGenres.setModel(genresModel);
    }

    private void clearForm() {
        tfName.setText("");
        lblNameError.setText("");
        lsGenres.clearSelection();

        btnNew.requestFocus();
    }

    @Override
    public boolean add(Object o) {
        Genre genre = new Genre((String) o);

        if (!genres.contains(genre)) {
            try {
                genre.setId(repository.genreCreate(genre));
                genres.add(genre);
                loadGenresModel();
                return true;
            } catch (Exception ex) {
                MessageUtils.showInformationMessage("Error", "Error adding genre");
                Logger.getLogger(GenresPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        return false;
    }
}
