//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WPFClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start App.
        /// </summary>
        public static string btnStartApp {
            get {
                return ResourceManager.GetString("btnStartApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading configuration.
        /// </summary>
        public static string errLoadConfig {
            get {
                return ResourceManager.GetString("errLoadConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load teams.
        /// </summary>
        public static string errLoadTeams {
            get {
                return ResourceManager.GetString("errLoadTeams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving settings.
        /// </summary>
        public static string errSaveConfig {
            get {
                return ResourceManager.GetString("errSaveConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings error.
        /// </summary>
        public static string errSettings {
            get {
                return ResourceManager.GetString("errSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to exit?.
        /// </summary>
        public static string exitConfirm {
            get {
                return ResourceManager.GetString("exitConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm exit.
        /// </summary>
        public static string exitConfirmTitle {
            get {
                return ResourceManager.GetString("exitConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Settings.
        /// </summary>
        public static string initialSettings {
            get {
                return ResourceManager.GetString("initialSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select championship:.
        /// </summary>
        public static string lblChampionship {
            get {
                return ResourceManager.GetString("lblChampionship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select data repository:.
        /// </summary>
        public static string lblDataRepository {
            get {
                return ResourceManager.GetString("lblDataRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select first team:.
        /// </summary>
        public static string lblFirstTeam {
            get {
                return ResourceManager.GetString("lblFirstTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draws:.
        /// </summary>
        public static string lblInfoDraws {
            get {
                return ResourceManager.GetString("lblInfoDraws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifa code:.
        /// </summary>
        public static string lblInfoFifaCode {
            get {
                return ResourceManager.GetString("lblInfoFifaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Games played:.
        /// </summary>
        public static string lblInfoGamesPlayed {
            get {
                return ResourceManager.GetString("lblInfoGamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals againts:.
        /// </summary>
        public static string lblInfoGoalsAgainst {
            get {
                return ResourceManager.GetString("lblInfoGoalsAgainst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals differential:.
        /// </summary>
        public static string lblInfoGoalsDifferential {
            get {
                return ResourceManager.GetString("lblInfoGoalsDifferential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals for:.
        /// </summary>
        public static string lblInfoGoalsFor {
            get {
                return ResourceManager.GetString("lblInfoGoalsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group:.
        /// </summary>
        public static string lblInfoGroupLetter {
            get {
                return ResourceManager.GetString("lblInfoGroupLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Losses:.
        /// </summary>
        public static string lblInfoLosses {
            get {
                return ResourceManager.GetString("lblInfoLosses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points:.
        /// </summary>
        public static string lblInfoPoints {
            get {
                return ResourceManager.GetString("lblInfoPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Team:.
        /// </summary>
        public static string lblInfoTeam {
            get {
                return ResourceManager.GetString("lblInfoTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wins:.
        /// </summary>
        public static string lblInfoWins {
            get {
                return ResourceManager.GetString("lblInfoWins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language:.
        /// </summary>
        public static string lblLanguage {
            get {
                return ResourceManager.GetString("lblLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain:.
        /// </summary>
        public static string lblPlayerInfoCaptain {
            get {
                return ResourceManager.GetString("lblPlayerInfoCaptain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals:.
        /// </summary>
        public static string lblPlayerInfoGoals {
            get {
                return ResourceManager.GetString("lblPlayerInfoGoals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string lblPlayerInfoName {
            get {
                return ResourceManager.GetString("lblPlayerInfoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture:.
        /// </summary>
        public static string lblPlayerInfoPicture {
            get {
                return ResourceManager.GetString("lblPlayerInfoPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position:.
        /// </summary>
        public static string lblPlayerInfoPosition {
            get {
                return ResourceManager.GetString("lblPlayerInfoPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number:.
        /// </summary>
        public static string lblPlayerInfoShirtNumber {
            get {
                return ResourceManager.GetString("lblPlayerInfoShirtNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow cards:.
        /// </summary>
        public static string lblPlayerInfoYellowCards {
            get {
                return ResourceManager.GetString("lblPlayerInfoYellowCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select second team:.
        /// </summary>
        public static string lblSecondTeam {
            get {
                return ResourceManager.GetString("lblSecondTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Settings.
        /// </summary>
        public static string lblTitle {
            get {
                return ResourceManager.GetString("lblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select window size:.
        /// </summary>
        public static string lblWindowSize {
            get {
                return ResourceManager.GetString("lblWindowSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF Client.
        /// </summary>
        public static string mainWindow {
            get {
                return ResourceManager.GetString("mainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Championship.
        /// </summary>
        public static string menuChampionship {
            get {
                return ResourceManager.GetString("menuChampionship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        public static string menuChampionshipMen {
            get {
                return ResourceManager.GetString("menuChampionshipMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        public static string menuChampionshipWomen {
            get {
                return ResourceManager.GetString("menuChampionshipWomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string menuLanguage {
            get {
                return ResourceManager.GetString("menuLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string menuLanguageCroatian {
            get {
                return ResourceManager.GetString("menuLanguageCroatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string menuLanguageEnglish {
            get {
                return ResourceManager.GetString("menuLanguageEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string menuSettings {
            get {
                return ResourceManager.GetString("menuSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ok {
            get {
                return ResourceManager.GetString("ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Player info.
        /// </summary>
        public static string playerInfo {
            get {
                return ResourceManager.GetString("playerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        public static string rbCroatian {
            get {
                return ResourceManager.GetString("rbCroatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string rbEnglish {
            get {
                return ResourceManager.GetString("rbEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string rbFile {
            get {
                return ResourceManager.GetString("rbFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen.
        /// </summary>
        public static string rbFullscreen {
            get {
                return ResourceManager.GetString("rbFullscreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1280x960.
        /// </summary>
        public static string rbLarge {
            get {
                return ResourceManager.GetString("rbLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1024x768.
        /// </summary>
        public static string rbMedium {
            get {
                return ResourceManager.GetString("rbMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men.
        /// </summary>
        public static string rbMen {
            get {
                return ResourceManager.GetString("rbMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 800x600.
        /// </summary>
        public static string rbSmall {
            get {
                return ResourceManager.GetString("rbSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web.
        /// </summary>
        public static string rbWeb {
            get {
                return ResourceManager.GetString("rbWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Women.
        /// </summary>
        public static string rbWomen {
            get {
                return ResourceManager.GetString("rbWomen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save settings?.
        /// </summary>
        public static string settingsSaveConfirm {
            get {
                return ResourceManager.GetString("settingsSaveConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm settings.
        /// </summary>
        public static string settingsSaveConfirmTitle {
            get {
                return ResourceManager.GetString("settingsSaveConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
